// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPrHEWIT-eRJDpukQ8jq1rtHGOZAmMFTk',
    appId: '1:962534036120:web:8d327f115225facf1fb6ed',
    messagingSenderId: '962534036120',
    projectId: 'chat--app-7fb19',
    authDomain: 'chat--app-7fb19.firebaseapp.com',
    storageBucket: 'chat--app-7fb19.appspot.com',
    measurementId: 'G-0SPEH6RRYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHeItPqHR-cJ1PN44q0HGWBr7Rl-CfWic',
    appId: '1:962534036120:android:91ceccd96b2abc591fb6ed',
    messagingSenderId: '962534036120',
    projectId: 'chat--app-7fb19',
    storageBucket: 'chat--app-7fb19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr4y-juYrvlV1C0J1UzToRJPRHLlaDYgA',
    appId: '1:962534036120:ios:46308f24442a43e31fb6ed',
    messagingSenderId: '962534036120',
    projectId: 'chat--app-7fb19',
    storageBucket: 'chat--app-7fb19.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr4y-juYrvlV1C0J1UzToRJPRHLlaDYgA',
    appId: '1:962534036120:ios:174c3509d0048b541fb6ed',
    messagingSenderId: '962534036120',
    projectId: 'chat--app-7fb19',
    storageBucket: 'chat--app-7fb19.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
